# Generated by Django 3.2.7 on 2021-11-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineSite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'vaccine_site',
                'verbose_name_plural': 'vaccine_sites',
                'db_table': 'vaccine_site',
            },
        ),
    ]
