@startuml editMember
       hide footbox
    center header \n<font color=black size=15>Edit Member</font> \n\n
skinparam dpi 150
skinparam sequence {
    LifeLineBorderColor #1F2833
    ArrowFontSize 10
    ArrowColor #1F2833
    ParticipantPediting 20
    ParticipantFontSize 12
    ParticipantFontColor #FFFFFF
    ParticipantBorderColor #14A098
    ParticipantBackgroundColor #14A098
}

skinparam ActorBorderColor #14A098
skinparam DatabaseBorderColor #14A098
    actor User
    participant webInterface
    participant editMemberAPI
    database DB
    User-> webInterface: 
    activate webInterface
    webInterface-> editMemberAPI: edit Member
    activate editMemberAPI
    editMemberAPI -> DB : save Member
    DB -> editMemberAPI : ok
    editMemberAPI -> webInterface: ok
    deactivate editMemberAPI
    webInterface->User
@enduml