# Generated by Django 3.2.7 on 2021-11-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependent', '__first__'),
        ('category', '0001_initial'),
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'vaccine_status',
                'verbose_name_plural': 'vaccine_status',
                'db_table': 'vaccine_status',
            },
        ),
        migrations.CreateModel(
            name='VaccineSchedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dose_number', models.IntegerField()),
                ('dose_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_schedule', to='dependent.dependent')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_schedule', to='category.category')),
                ('status_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vaccine_schedule.vaccinestatus')),
                ('vaccine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccine')),
            ],
            options={
                'verbose_name': 'vaccine_schedule',
                'verbose_name_plural': 'vaccine_schedules',
                'db_table': 'vaccine_schedule',
                'ordering': ('dose_number', 'vaccine_id'),
            },
        ),
    ]
